#!/bin/bash
# Script for running VMWare Fusion headless instances.

VM_IMAGE_DIR="/Users/alex/Documents/Virtual Machines.localized/"
VM_IMAGE=fusion6\\centos\\64x\\minimal\\LAMP.vmwarevm/fusion6\\centos\\64x\\minimal\\LAMP.vmx


vmrun -T fusion $1 "$VM_IMAGE_DIR$VM_IMAGE" nogui

